spring:
  application:
    name: kontrolBankData

  thymeleaf:
    cache: false

  config:
    import: optional:file:./config/database.yaml

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
