spring:
  application:
    name: kontrolBankData

  thymeleaf:
    cache: false

  config:
    import: optional:file:./config/database.yaml

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    database-platform: org.hibernate.community.dialect.MySQLLegacyDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
