/* Структура БД берется из готового дампа. Файл оставлен только как справка.

CREATE TABLE IF NOT EXISTS delivery_org (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "User" varchar(40) NOT NULL UNIQUE,
    "PWD" varchar(8)
);

CREATE TABLE IF NOT EXISTS vozv_bank (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Number_VD" varchar(7),
    "FIO_Recipient" varchar(200),
    "NameBank" varchar(255),
    "Type_Vozv" varchar(30),
    "Number_package" varchar(10),
    "Month" integer,
    "Year" integer,
    "Prichina" varchar(255),
    "Period" varchar(255),
    "Srochnost" varchar(4),
    "Area" integer,
    "Primechanie_ONiVBD" varchar(255)
);

CREATE TABLE IF NOT EXISTS vozv_sed (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Number_VD" varchar(7),
    "FIO_Recipient" varchar(255),
    "Number_Package" varchar(10),
    "Month" integer,
    "Year" integer,
    "Prichina" varchar(255),
    "Srochnost" varchar(5),
    "FIO_SP_ONiVB" varchar(255),
    "Primechanie_ONiVB" varchar(255),
    "Ot_Ispolnenie" varchar(20),
    "FIO_OVVBD" varchar(255),
    "Primechanie_OVVBD" varchar(255),
    "Area" integer
);

CREATE TABLE IF NOT EXISTS razovie_rr (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Number_VD" varchar(10),
    "FIO_Recipient" varchar(255),
    "Uchet_V" varchar(20),
    "Prichina_oformleniay_rv" varchar(100),
    "Type_Pay" varchar(20),
    "Istochnik" varchar(20),
    "Amount" varchar(20),
    "Period_rv" varchar(200),
    "Srochnost" varchar(5),
    "FIO_SP_ONiVP" varchar(255),
    "Primechanie_ONiVB" varchar(255),
    "Ot_ispolneniay" varchar(20),
    "FIO_SP_OVVBD" varchar(255),
    "Primechanie_OVVBD" varchar(200),
    "Result_kontr_1" varchar(30),
    "FIO_SP_KRO_1" varchar(255),
    "Result_kontr_2" varchar(30),
    "FIO_SP_KRO_2" varchar(255),
    "Area" integer
);*/
